[build]
  base = "frontend/app"
  publish = "dist"
  command = "npm run build"

[build.environment]
  VUE_APP_API_URL = "https://messagegenerator-backend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200